### ISSUE TITLE
Possible to document arbitrary code files, like cpp, ruby, or typescript?

### ISSUE THREAD

**Issue by trusktr** [marijnh/getdocs#13]
I'm looking for a tool that won't stumble on the code.

So far, every JSDoc or TSDoc tool has some problems, because they all rely on the underlying code to infer features, or for parsing, or whatever reason, and eventually they all do what I don't want them to do (crash, infer too much, etc).

What I need, is a tool that will take my comments as the source of truth and completely ignore any and all code, including code that it can not understand.

Can I do this with getdocs?

F.e., if I supply names and types, can I make it completely ignore all code source, and only read my comments?

**Comment by marijnh** [comment]
Not really. This tool is designed to use the context of the doc comments to infer additional information (symbol names, kind of symbol, class structure, etc), and as such is quite closely tied to a JavaScript syntax tree.

**Comment by trusktr** [comment]
Ah ok. Thanks! Would be neat to have a context-free mode. I like the syntax. 👍
