### ISSUE TITLE
Support documentation for parameters and returns

### ISSUE THREAD

**Issue by angelozerr** [marijnh/getdocs#5]
It should be cool if we could add documentation for parameters and returns fucntion. An idea:

```javascript
// :: (number{doc for arg0}, number{doc for arg1}) → number{doc for returns}
// Add two numbers
export function plus(a, b = 2) {
  return a + b
}
```

ternjs has the same issue https://github.com/ternjs/tern/issues/691

**Comment by marijnh** [comment]
Nope, I am intentionally not including this feature. I think the format of a simple signature plus a number of paragraphs that document the function and its parameters work well.
