### ISSUE TITLE
What if an argument accepts multiple types?

### ISSUE THREAD

**Issue by ericandrewlewis** [marijnh/getdocs#7]
I'm looking to document [this function](https://github.com/ericandrewlewis/prosemirror/blob/master/src/dom/index.js#L1-L11).

The third parameter accepts string, array, or DOM element. How would one document this?

**Comment by marijnh** [comment]
I'm using `union<string, [...], DOMNode>` for situations like that. Though in this case, since the type is recursive (the `...` should refer to the union itself) you can't really do that accurately.
