### ISSUE TITLE
Status/future?

### ISSUE THREAD

**Issue by wavded** [marijnh/getdocs#9]
Hey @marijnh, I like what I've seen so far and played with for this project.  Curious as to what the status is on things like supporting CommonJS and TernJS integration?  Also, have any doc generators been built yet that you are aware of?

Thanks much!

**Comment by marijnh** [comment]
Hi. This is, so far, just something that I'm building to support the use cases I have -- documenting ProseMirror. ProseMirror currently uses CommonJS, though it does use a specific export pattern (declare normally, export in a separate statement) to work well with getdocs. The only library I know of that consumes this stuff currently is [builddocs](https://github.com/marijnh/builddocs), the thing I'm using to generate [these docs](http://prosemirror.net/ref.html)
